name: flutter_flow_chart
description: draw a flow chart diagram with different kind of customizable elements. Dashboards can be saved for later use.
version: 3.2.3
homepage: https://github.com/alnitak/flutter_flow_chart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/uuid
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
